import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import { TechnicalResult, ApplianceLoad } from "./solar-logic";
import { formatCurrency } from "./constants";

interface ReportData {
    clientName: string;
    loads: ApplianceLoad[];
    results: TechnicalResult;
}

export const generateSolarPDF = async (data: ReportData) => {
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();

    // -- HEADER --
    doc.setFillColor(10, 31, 68); // Brand Navy
    doc.rect(0, 0, pageWidth, 40, "F");

    doc.setTextColor(255, 255, 255);
    doc.setFontSize(22);
    doc.setFont("helvetica", "bold");
    doc.text("SOLAR ENGINEERING REPORT", 14, 20);

    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    doc.text(`Prepared for: ${data.clientName}`, 14, 30);
    doc.text(`Date: ${new Date().toLocaleDateString()}`, pageWidth - 50, 30);

    // -- SUMMARY CARDS --
    let yPos = 50;

    doc.setTextColor(10, 31, 68);
    doc.setFontSize(14);
    doc.setFont("helvetica", "bold");
    doc.text("System Specification Summary", 14, yPos);

    yPos += 10;
    const cards = [
        { title: "Solar Array", value: `${data.results.panelCount}x`, sub: "450W Panels" },
        { title: "Inverter", value: `${data.results.requiredInverterKVA} kVA`, sub: "Pure Sine Wave" },
        { title: "Battery Bank", value: `${data.results.batteryCount}x`, sub: "200Ah 12V" },
    ];

    cards.forEach((card, i) => {
        const xMode = 14 + (i * 65);
        doc.setDrawColor(200, 200, 200);
        doc.setFillColor(248, 250, 252);
        doc.roundedRect(xMode, yPos, 60, 30, 3, 3, "FD");

        doc.setFontSize(10);
        doc.setTextColor(100, 100, 100);
        doc.text(card.title, xMode + 5, yPos + 10);

        doc.setFontSize(16);
        doc.setTextColor(10, 31, 68);
        doc.setFont("helvetica", "bold");
        doc.text(card.value, xMode + 5, yPos + 20);

        doc.setFontSize(8);
        doc.setFont("helvetica", "normal");
        doc.text(card.sub, xMode + 5, yPos + 26);
    });

    // -- LOAD ANALYSIS --
    yPos += 45;
    doc.setFontSize(14);
    doc.setTextColor(10, 31, 68);
    doc.text("Load Profile Analysis", 14, yPos);

    const tableBody = data.loads.map(l => [
        l.name,
        `${l.wattage} W`,
        l.quantity,
        `${l.hoursPerDay} hrs`,
        `${((l.wattage * l.quantity * l.hoursPerDay) / 1000).toFixed(2)} kWh`
    ]);

    autoTable(doc, {
        startY: yPos + 5,
        head: [['Appliance', 'Rating', 'Qty', 'Daily Run', 'Energy']],
        body: tableBody,
        headStyles: { fillColor: [46, 204, 113] }, // Brand Green
        foot: [['', '', '', 'TOTAL LOAD:', `${data.results.totalDailyLoadKWh} kWh/day`]],
        footStyles: { fillColor: [10, 31, 68], textColor: [255, 255, 255], fontStyle: 'bold' }
    });

    // -- FINANCIALS --
    // @ts-ignore
    yPos = doc.lastAutoTable.finalY + 20;

    doc.setFontSize(14);
    doc.setTextColor(10, 31, 68);
    doc.text("Financial Projection", 14, yPos);

    yPos += 10;
    doc.setFontSize(10);
    doc.setTextColor(50, 50, 50);
    doc.text(`Estimated System Cost: ${formatCurrency(data.results.estimatedCost.min)} - ${formatCurrency(data.results.estimatedCost.max)}`, 14, yPos);

    yPos += 8;
    doc.text(`Estimated Annual Savings: ${formatCurrency(data.results.savingsPerYear)}`, 14, yPos);

    yPos += 8;
    const paybackYears = (data.results.estimatedCost.min / data.results.savingsPerYear).toFixed(1);
    doc.text(`Estimated Payback Period: ${paybackYears} Years`, 14, yPos);

    // Footer
    doc.setFontSize(8);
    doc.setTextColor(150, 150, 150);
    doc.text("Generated by MSE Solar Estimator. Estimates are for planning purposes only.", 14, 280);

    doc.save(`MSE_Solar_Report_${data.clientName.replace(/\s+/g, '_')}.pdf`);
};
